# Generated by Django 4.1.7 on 2023-03-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_remove_ideasmodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ideasmodel',
            old_name='About_contributing',
            new_name='About_contributor',
        ),
        migrations.AddField(
            model_name='ideasmodel',
            name='Title',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ideasmodel',
            name='Budget',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ideasmodel',
            name='Contact_email',
            field=models.EmailField(max_length=254),
        ),
    ]
