# Generated by Django 4.1.7 on 2023-03-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorhub', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
