# Generated by Django 4.1.7 on 2023-03-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsorpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=50)),
                ('business_industry', models.CharField(max_length=100)),
                ('about_sponsor', models.TextField()),
                ('budget', models.IntegerField(default=5000)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
