# Generated by Django 4.1.7 on 2023-03-03 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsorpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=50)),
                ('about_sponsor', models.TextField()),
                ('business_industry', models.CharField(max_length=100)),
                ('budget', models.IntegerField(default=5000, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(500000)])),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
