# Generated by Django 4.1.7 on 2023-03-15 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_app', '0002_sponsorpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
