# Generated by Django 4.1.7 on 2023-03-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_app', '0002_sponsorpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorpost',
            name='budget',
            field=models.IntegerField(default=5000),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
