# Generated by Django 4.1.7 on 2023-03-20 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_app', '0003_alter_sponsorpost_budget_delete_post'),
        ('sponsor_app', '0003_delete_post'),
    ]

    operations = [
    ]
