# Generated by Django 4.1.7 on 2023-03-22 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_app', '0004_alter_sponsorpost_budget'),
        ('sponsor_app', '0004_merge_20230320_1922'),
    ]

    operations = [
    ]
